<?php

namespace AppBundle\Repository;

/**
 * RegimentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegimentRepository extends \Doctrine\ORM\EntityRepository
{
}
