<?php

namespace AppBundle\Repository;

/**
 * WkuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WkuRepository extends \Doctrine\ORM\EntityRepository
{
}
